# Generated by Django 5.2.1 on 2025-05-14 22:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Аталышы')),
                ('author', models.CharField(max_length=255, verbose_name='Автору')),
                ('isbn', models.CharField(max_length=20, unique=True, verbose_name='ISBN')),
                ('year_published', models.PositiveIntegerField(blank=True, null=True, verbose_name='Басылган жылы')),
                ('quantity_total', models.PositiveIntegerField(default=1, verbose_name='Жалпы саны')),
                ('quantity_available', models.PositiveIntegerField(default=1, verbose_name='Жеткиликтүү саны')),
                ('genre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Жанры')),
                ('image_cover', models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Китептин сүрөтү')),
                ('loan_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Канча жолу алынган')),
            ],
            options={
                'verbose_name': 'Китеп',
                'verbose_name_plural': 'Китептер',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50, unique=True, verbose_name="Колдонуучунун ID'си")),
                ('name', models.CharField(max_length=200, verbose_name='Аты-жөнү')),
                ('user_type', models.CharField(choices=[('student', 'Окуучу'), ('teacher', 'Мугалим')], max_length=10, verbose_name='Колдонуучунун тиби')),
            ],
            options={
                'verbose_name': 'Карыз алуучу',
                'verbose_name_plural': 'Карыз алуучулар',
            },
        ),
        migrations.CreateModel(
            name='Librarian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Аты-жөнү')),
                ('employee_id', models.CharField(max_length=50, unique=True, verbose_name='Кызматтык ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='librarians/', verbose_name='Сүрөтү')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Кошумча маалымат')),
            ],
            options={
                'verbose_name': 'Китепканачы',
                'verbose_name_plural': 'Китепканачылар',
            },
        ),
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('loan_date', models.DateField(default=django.utils.timezone.now, verbose_name='Берилген күнү')),
                ('due_date', models.DateField(verbose_name='Кайтаруу мөөнөтү')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='Кайтарылган күнү')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='api.book', verbose_name='Китеп')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='api.borrower', verbose_name='Карыз алуучу')),
            ],
            options={
                'verbose_name': 'Китеп берүү/кайтаруу жазуусу',
                'verbose_name_plural': 'Китеп берүү/кайтаруу жазуулары',
                'ordering': ['-loan_date'],
            },
        ),
    ]
